version: '3'

volumes:
  pg_data_production:
  static_volume:
  frontend_static_volume:
  media_volume:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: mpolshkov/foodgram_backend
    env_file: .env
    volumes:
      - static_volume:/app/backend_static
      - media_volume:/app/media
    depends_on:
      - db
  frontend:
    env_file: .env
    image: mpolshkov/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - frontend_static_volume:/frontend_static
  gateway:
    image: mpolshkov/foodgram_gateway
    env_file: .env
    ports:
      - 80:80
    volumes:
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/var/static
      - media_volume:/var/media
      - frontend_static_volume:/var/frontend/
    depends_on:
      - db
      - backend
      - frontend